services:
  go:
    build:
      context: .
      dockerfile: ./build/Dockerfile
    container_name: go
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - ./:/usr/src/app
      - db:/usr/src/app/db
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    ports:
      - 3306:3306
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql
  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    ports:
      - 8025:8025
volumes:
  db:
    driver: 'local'
