development:
  dialect: mysql
  datasource: root:password@tcp(mysql:3306)/wiki?parseTime=true&collation=utf8mb4_general_ci&interpolateParams=true
  dir: migrations

test:
  dialect: mysql
  datasource: root:password@tcp(mysql:3306)/test?parseTime=true&collation=utf8mb4_general_ci&interpolateParams=true
  dir: migrations
